### ISSUE TITLE
Installation support

### ISSUE THREAD

**Issue by sMauldaeschle** [MCrissDev/HANotify#2]
Hi, it reads like it is a great function but I cannot manage to get it installed. Did something change, because for most people it seems to work. Do I just have to copy the py-file in the right place and add the three lines to the configuration.yaml, set an Api password and restart the Raspberry? I am wondering why https://github.com/Crewski/HANotify has so many files. Do I also need to install the apk on the Android device like mentioned there and can I ignore all remaining files?
Sorry if I am asking easy questions but also with google and reading many of the comments I did not manage to get it work. In the Android App "Home Assistant Notify" I always get a "Something went wrong error.". It doesn't matter if I am using the local IP or DNS. Api password is set by the way.

**Comment by MCrissDev** [comment]
Hello,
Please fallow instructions from http://ariela.surodev.com/2018/11/08/push-notifications/
Also note that this component will only work with Ariela.
Please let me know if works and sorry for late response.
Ionut

**Comment by WaaZaa666** [comment]
@MCrissDev I'm trying to get the notifications to work as well, but to no avail. 

I keep getting the following message when enabling/disabling firebase in the app: 
![image](https://user-images.githubusercontent.com/28536686/53481524-aed49080-3a7d-11e9-9dd6-689cf3847000.png)

I do have the custom component installed, since logging logs: 
"You are using a custom component for fcm-android.notify which has not been tested by Home Assistant."

When trying to call the service: 
![image](https://user-images.githubusercontent.com/28536686/53481625-e8a59700-3a7d-11e9-8c70-d933ad7b73db.png)

Also, I do not see the fcm_android_registrations.conf file being created anywhere on the home assistant filesystem. 

Any thoughts?

**Comment by MCrissDev** [comment]
Hello,

Please fallow instructions from http://ariela.surodev.com/2018/11/08/push-notifications/
If you still not able to make it work, please enable debug mode in Ariela and send me the logs. Thank you.

**Comment by WaaZaa666** [comment]
I did follow the instructions. Logs will be incoming!

**Comment by MCrissDev** [comment]
Hello,
Is this issue resolved using latest Ariela version?

**Comment by WaaZaa666** [comment]
Not yet. I still see a version of 26feb in play store...

**Comment by MCrissDev** [comment]
Well, since then 3 version been uploaded. Please retry refreshing and update. Thank you.

**Comment by WaaZaa666** [comment]
Finally got the update by play store. Needed to wipe settings, but after
that it worked!

Thanks again

**Comment by MCrissDev** [comment]
Glad to hear that.
